"""empty message

Revision ID: 180277dda4de
Revises: 
Create Date: 2024-03-28 19:44:43.975559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180277dda4de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('plan_cost', sa.Float(), nullable=False),
    sa.Column('plan_validity', sa.Integer(), nullable=False),
    sa.Column('plan_status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_name')
    )
    op.create_table('user',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('aadhar_number', sa.String(length=12), nullable=False),
    sa.Column('registration_date', sa.String(length=10), nullable=False),
    sa.Column('mobile_number', sa.String(length=10), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhar_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('mobile_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('plan')
    # ### end Alembic commands ###
